// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOe8ex07xdtkQTh5GOSPbiGk-_xEUysao',
    appId: '1:1048358993447:android:d65553a330cf77e576d802',
    messagingSenderId: '1048358993447',
    projectId: 'subtitle-downloader-1580b',
    storageBucket: 'subtitle-downloader-1580b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkDwXluqF0uamjFi-2p3G5I2csU7AUKc4',
    appId: '1:1048358993447:ios:b821b2d96d5a609676d802',
    messagingSenderId: '1048358993447',
    projectId: 'subtitle-downloader-1580b',
    storageBucket: 'subtitle-downloader-1580b.appspot.com',
    androidClientId: '1048358993447-0jj3flui7e6fcg4f6f638qpu4fol5j36.apps.googleusercontent.com',
    iosClientId: '1048358993447-dbm99jlmpn9v7nq3aj7jehvr8lmfdec2.apps.googleusercontent.com',
    iosBundleId: 'com.zouheirn.subtitledownloader.subtitleDownloader',
  );
}
